version: '3'
services:
  back-http:
    image: nginx:latest
    ports:
      - 80:80
  haproxy:
    build: ./haproxy
    depends_on: 
      - back-http
    ports:
      - 10080:80
      - 10443:443
  hitch:
    build: ./hitch
    depends_on:
      - back-http
    ports:
      - 11443:443

